### ISSUE TITLE
Who pays gas for blockchain fingerprinting?

### ISSUE THREAD

**Issue by ot-github-reporter** [OriginTrail/Improvement-Proposals#7]
<h1>Simple Summary</h1><p>Is the DH responsible for payign any tx fees associated with &quot;daily&quot; stamping updated graphs (hashed versions) onto the appropriate blockchain?</p>
<p>Irresepctive of whether the DH draws his/her rewards over time or at the end of an agreement</p><h1>Abstract</h1><h1>Motivation</h1><h1>Specification</h1><h1>Rationale</h1><h1>Backwards Compatibility</h1><h1>Test Cases</h1><h1>Implementation</h1>

**Comment by schrink** [comment]
In this phase of development - yes. However, if you have a proposal, please fill in the form and we will carefully consider your proposal. This is rather question than proposal. 

Thanks!
